### ISSUE TITLE
to-do 

### ISSUE THREAD

**Issue by Skylar1013** [Garden-Girls/a8#3]
BEFORE VIDEO:
- [ ] add plant page styling
- [x] entry page styling
- [ ] header stuff
- [x] delete age
- [x] add a footer "add"
- [x] change species
- [x] "add plant" footer doesn't show up
------------------
- [ ] filter for search page, beginner, intermediate...
- [ ] delete color coding on calendar page
- [ ] nickname
